apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: configserver-deploy
  namespace: shoppingportal
spec:
  replicas: 1
  selector:
    matchLabels:
      name: configserver
      zone: prod
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        name: configserver
        version: v1
        release: stable
        tier: fe
        zone: prod
        managed-by: m2
    spec:
      containers:
        - name: configserver-ctr
          image: metamagicglobal/config-wk
          imagePullPolicy: Always
          ports:
          - containerPort: 6061
       