apiVersion: v1
kind: Service
metadata:
  name: productservicems
  namespace: shoppingportal
spec:
  selector: 
    name: productservicems
  ports:
  - protocol: TCP
    targetPort: 8081
    port: 80
    name: http