server:
  port: 8081   

spring:
  profiles: dev_env
  application:
    name: productservice    
eureka:
  instance:
    ip-address: false
    lease-renewal-interval-in-seconds: 5
    metadata-map:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    serviceUrl:
      defaultZone: http://eurekaserverservice.shoppingportal.svc.cluster.local/eureka-server/eureka/